server:
  port: 8102

info:
  app:
    description: Quotation Service
    name: Quotation Service
    version: 1.0.0

app:
  quotation:
    expiryTime: 1440
  customerSrvUrl: http://localhost:8103
  productSrvUrl: http://localhost:8101
  customerSrv: customer-srv
  productSrv: product-srv

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/

spring:
  application:
    name: quotation-srv
  data:
    mongodb:
      uri: mongodb://localhost:27017/insurance
#      username: spring-app-user
#      password: spring
#      database: insurance
#      port: 27017
#      host: localhost

#logging:
#  level:
#    space.gavinklfong: DEBUG