server:
  port: 8102

info:
  app:
    description: Quotation Service
    name: Quotation Service
    version: 1.0.0

app:
  quotation:
    expiryTime: 1440
  customerSrvUrl: http://localhost:8103
  productSrvUrl: http://localhost:8101

spring:
  application:
    name: quotation-srv
  data:
    mongodb:
      uri: mongodb://localhost:27017/insurance
